<a href="https://colab.research.google.com/github/BeomJinPNU/202006136/blob/main/24_05_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# 2번째 시험 문제
# N개의 숫자가 공백없이 입력, 이 숫자를 모두 합쳐서 출력
Num = input()
NUM_List = list(Num)
aa = map(int,NUM_List)
print(sum(aa))

1234
10


In [ ]:
# 3번째 시험 문제
# 다음 리스트에서 확장자가 png나 jpg인 파일명.확장자를 출력하는 파이썬 코드를 작성하시오
# 첫째 줄에 숫자 N, 둘째 줄부터는 파일명이 하나씩 주어짐.
# 결과가 리스트로 출력
a=list(map(str, input().split()))
n=int(input())
a=[input() for _ in range(n)]
b=[i for i in a if i.split('.',)]

In [5]:
import numpy as np
print(np.__version__)

1.25.2


# 넘파이의 ndarray 클래스의 기본 속성 5가지 중요!
shape, size, ndim, nbyte, dtype

In [20]:
import numpy as np
arr = np.arange(1, 10, 2)
print(arr)

x = np.ones((3,4))
print(x)
print('size :', x.size)
print('dtype :', x.dtype)
print('shape :', x.shape)
print('ndim :', x.ndim)

y = np.linspace(0, 1, 10)
print(y)


[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
size : 12
dtype : float64
shape : (3, 4)
ndim : 2
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [21]:
arr1 = np.array([[1,2,3],
[4,5,6],
[7,8,9]])
print(arr1[0])
print(arr1[0,2])
print(arr1[1:])
print(arr1[arr1 > 5])

[1 2 3]
3
[[4 5 6]
 [7 8 9]]
[6 7 8 9]


In [49]:
A=np.array([np.arange(1,6),np.arange(6,11),np.arange(11,16),np.arange(16,21),np.arange(21,26)])
print(A)
print(A[3,3])
print(A[:2,:2])
print(A[3:,3:])
print(A[0],A[1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[1 2 3 4 5] [ 6  7  8  9 10]


In [63]:
A=np.arange(1,37)
A=A.reshape(3, 3, 4)
print(A)

A=A.reshape(3, 4, 3)
print(A)

A=A.flatten()
print(A)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
